linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustivestruct
    - exhaustruct
    - golint
    - interfacer
    - maligned
    - nlreturn
    - scopelint
    - varnamelen
    - wsl

linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US
